#!/usr/bin/env python3
"""Generate bin/ launchers for gptme core and every gptme-contrib package.
(Normally run through admin/install-tools.sh.)

Each launcher resolves uv through mise, then runs the tool with
`uv tool run --from <pinned spec>`. mise's pipx backend drops `#subdirectory=`
fragments, so uv does the package install and mise only provides the runtimes.

The pins live here (CONTRIB_URL/CONTRIB_REF/GPTME_SPEC) and nowhere else.
Re-run after bumping a pin or after the contrib submodule gains a package:

    python3 scripts/gen-bin.py
"""

import re
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PACKAGES = ROOT / "gptme-contrib" / "packages"
BIN = ROOT / "bin"

CONTRIB_URL = "git+https://github.com/skogai2/gptme-contrib.git"
CONTRIB_REF = "skogai-2026.10.02"
GPTME_SPEC = "gptme[server,acp]==0.34.0"

# gptme core's console scripts (from `pip show -f gptme` at GPTME_SPEC).
GPTME_SCRIPTS = [
    "gptme", "gptme-acp", "gptme-agent", "gptme-attest", "gptme-auth",
    "gptme-checkpoint", "gptme-convert", "gptme-dataset", "gptme-doctor",
    "gptme-dspy", "gptme-eval", "gptme-eval-swebench", "gptme-eval-tbench",
    "gptme-eval-trends", "gptme-init", "gptme-mcp-server", "gptme-onboard",
    "gptme-resume", "gptme-server", "gptme-service", "gptme-stats",
    "gptme-status", "gptme-tui", "gptme-tutorial", "gptme-util", "gptme-wut",
]  # fmt: skip

TEMPLATE = """\
#!/bin/bash
# Generated by scripts/gen-bin.py -- do not edit.
ROOT="$(cd "$(dirname "$(readlink -f "${{BASH_SOURCE[0]}}")")/.." && pwd)"
# Shared machine install (admin/install-tools.sh): agents have no mise or uv of
# their own, so use the runtimes under $ROOT/tools/mise. Elsewhere (containers)
# mise's default data dir is used.
[ -d "$ROOT/tools/mise" ] && export MISE_DATA_DIR="${{MISE_DATA_DIR:-$ROOT/tools/mise}}"
export MISE_TRUSTED_CONFIG_PATHS="$ROOT${{MISE_TRUSTED_CONFIG_PATHS:+:$MISE_TRUSTED_CONFIG_PATHS}}"
UV="$(mise -C "$ROOT" which uv 2>/dev/null)" || UV=uv
exec "$UV" tool run --from "{spec}"{withs} {cmd} "$@"
"""


def contrib_spec(pkg: str) -> str:
    return f"{CONTRIB_URL}@{CONTRIB_REF}#subdirectory=packages/{pkg}"


def write(cmd: str, spec: str, withs: list[str]) -> None:
    extra = "".join(f' --with "{w}"' for w in withs)
    path = BIN / cmd
    # bin/ may hold a symlink from an older install; writing through it would
    # overwrite the target (e.g. a venv's entry script).
    path.unlink(missing_ok=True)
    path.write_text(TEMPLATE.format(spec=spec, withs=extra, cmd=cmd))
    path.chmod(0o755)


def main() -> None:
    BIN.mkdir(exist_ok=True)
    for old in BIN.iterdir():
        if old.is_symlink():
            continue  # not ours; write() replaces it only if a launcher claims the name
        if old.is_file() and "Generated by scripts/gen-bin.py" in old.read_text():
            old.unlink()

    for cmd in GPTME_SCRIPTS:
        write(cmd, GPTME_SPEC, [])

    count = len(GPTME_SCRIPTS)
    for pyproject in sorted(PACKAGES.glob("*/pyproject.toml")):
        data = tomllib.loads(pyproject.read_text())
        scripts = data.get("project", {}).get("scripts", {})
        if not scripts:
            continue
        sources = data.get("tool", {}).get("uv", {}).get("sources", {})
        # uv workspace siblings can't be resolved from a bare git subdirectory.
        withs = [
            contrib_spec(name)
            for name, src in sources.items()
            if isinstance(src, dict) and src.get("workspace")
        ]
        # Packages declare a bare `mcp>=1.0`, which now resolves to mcp 2.x
        # where FastMCP is gone (`mcp.server.fastmcp` import fails).
        project = data.get("project", {})
        deps = list(project.get("dependencies", []))
        for extra in project.get("optional-dependencies", {}).values():
            deps += extra
        if any(re.match(r"mcp\b", dep) for dep in deps):
            withs.append("mcp<2")
        for cmd in scripts:
            write(cmd, contrib_spec(pyproject.parent.name), withs)
            count += 1
    print(f"wrote {count} launchers to {BIN}")


if __name__ == "__main__":
    main()
